MCU = RP2040
BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040

VIA_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_ENABLE = no
WPM_ENABLE = no
MIDI_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
TAP_DANCE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

OLED_ENABLE = yes
LTO_ENABLE = yes
COMBO_ENABLE = yes
